#' @title
#'   Create a new Monty Hall Problem game.
#'
#' @description
#'   'create_game()' generates a new game that consists of two doors
#'   with goats behind them, and one with a car.
#'
#' @details
#'   The game setup replicates the game on the TV show "Let's
#'   Make a Deal" where there are three doors for a contestant
#'   to choose from, one of which has a car behind it and two
#'   have goats. The contestant selects a door, then the host
#'   opens a door to reveal a goat, and then the contestant is
#'   given an opportunity to stay with their original selection
#'   or switch to the other unopened door. There was a famous
#'   debate about whether it was optimal to stay or switch when
#'   given the option to switch, so this simulation was created
#'   to test both strategies.
#'
#' @param ... no arguments are used by the function.
#'
#' @return The function returns a length 3 character vector
#'   indicating the positions of goats and the car.
#'
#' @examples
#'   create_game()
#'
#' @export
create_game <- function()
{
  a.game <- sample( x=c("goat","goat","car"), size=3, replace=F )
  return( a.game )
}



#' @title
#'  Contestant selects a door.
#' @description
#'  'select_door()' randomly selects a number from 1-3 and
#'   matches a door generated by the create_game() function.
#' @details
#'  The randomly generated numbers of 1-3 created by this
#'  function correspond to either a "car" or a "goat" door,
#'  as determined by the create_game() function.
#' @param ... no arguments are used by the function.
#' @return  The function returns a numeric vector of 1, 2, or 3.
#' @examples
#'   select_door()
#' @export
select_door <- function( )
{
  doors <- c(1,2,3)
  a.pick <- sample( doors, size=1 )
  return( a.pick )  # number between 1 and 3
}



#' @title
#'  Host opens a goat door.
#' @description
#'  The function 'open_goat_door()' selects one of the two remaining
#'  doors.
#' @details
#'  'open_goat_door()' functions in one of two ways. If the contestant
#'  selects one of the two "goat" doors, then the function opens the
#'  remaining "goat" door. But if the contestant selects the "car"
#'  door, the function randomly picks one of two unopened "goat" doors.
#' @param ... no arguments are used by the function.
#' @return  The function returns a numeric vector of 1, 2, or 3 that
#'          represents the door the host picks and is different from
#'          the one chosen by 'select_door()' (a.pick). The return is
#'          then saved as 'opened.door'.
#' @examples
#'   open_goat_door( game, a.pick )
#' @export
open_goat_door <- function( game, a.pick )
{
  doors <- c(1,2,3)
  # if contestant selected car,
  # randomly select one of two goats
  if( game[ a.pick ] == "car" )
  {
    goat.doors <- doors[ game != "car" ]
    opened.door <- sample( goat.doors, size=1 )
  }
  if( game[ a.pick ] == "goat" )
  {
    opened.door <- doors[ game != "car" & doors != a.pick ]
  }
  return( opened.door ) # number between 1 and 3
}



#' @title
#'  Contest chooses to stay or switch.
#' @description
#'  In this function, 'change_door()', the argument "stay" represents the
#'  contestant keeping their original choice or switching to the other
#'  remaining door.
#' @details
#'  Again, a binary choice emerges. If the contestant stays with
#'  their original choice (stay=T), then 'a.pick' remains the same.
#'  However, if the contestant chooses to switch to the other remaining
#'  door, then the vector that is not represented by 'a.pick' or
#'  'opened.door' is selected.
#' @param   "T" or "F", representing TRUE and FALSE, respectively,
#'          decide whether the contest stays or remains.
#' @return  The function returns a number of 1-3 that does not match
#'          'opened.door'.
#'
#' @examples
#'   change_door(stay=T, opened.door, a.pick)
#'   change_door(stay=F, opened.door, a.pick)
#'
#' @export
change_door <- function( stay=T, opened.door, a.pick )
{
  doors <- c(1,2,3)
  
  if( stay )
  {
    final.pick <- a.pick
  }
  if( ! stay )
  {
    final.pick <- doors[ doors != opened.door & doors != a.pick ]
  }
  
  return( final.pick )  # number between 1 and 3
}



#' @title
#'  Determine whether the contestant has won.
#' @description
#'  If the contests ends the game with a "car" door,
#'  determine_winner returns their winning status.
#' @details
#'  'determine_winner()' uses the status of 'final.pick' and 'game'
#'  to determine if the contestant has won.
#' @param ... no arguments are used by this function.
#' @return  If 'final_pick' is equal to "car", then the function
#'          returns "WIN". If 'final_pick' is equal to "goat", then
#'          the function returns "Lose".
#' @examples
#'   determine_winner(final.pick, game)
#' @export
determine_winner <- function( final.pick, game )
{
  if( game[ final.pick ] == "car" )
  {
    return( "WIN" )
  }
  if( game[ final.pick ] == "goat" )
  {
    return( "LOSE" )
  }
}





#' @title
#'  Play the Monty Hall Problem game.
#' @description
#'  'play_game()' returns the outcome of each game
#'  every time it is run.
#' @details
#'  Using the results from 'create_game()', 'select_door()',
#'  'open_goat_door()', 'change_door()', and 'determine_winner()',
#'  this function completes a Monty Hall Problem game and records its
#'  outcomes in a table.
#' @param ... no arguments are used by this function.
#' @return  This function returns a table with the outcome (WIN or LOSE)
#'          associated with each strategy (stay or switch).
#' @examples
#'   play_game()
#' @export
play_game <- function( )
{
  new.game <- create_game()
  first.pick <- select_door()
  opened.door <- open_goat_door( new.game, first.pick )
  
  final.pick.stay <- change_door( stay=T, opened.door, first.pick )
  final.pick.switch <- change_door( stay=F, opened.door, first.pick )
  
  outcome.stay <- determine_winner( final.pick.stay, new.game  )
  outcome.switch <- determine_winner( final.pick.switch, new.game )
  
  strategy <- c("stay","switch")
  outcome <- c(outcome.stay,outcome.switch)
  game.results <- data.frame( strategy, outcome,
                              stringsAsFactors=F )
  return( game.results )
}






#' @title
#'  Looping play game.
#' @description
#'  The function 'play_n_games()' will simulate n number of Monty
#'  Hall Problem games and return the table of outcomes.
#' @details
#'  'play_n_games()' will automatically run the game as many n times
#'  as selected. In addition, the function will return the results
#'  associated with each strategy (stay or switch) as a proportion
#'  to two decimal places.
#' @param   n equals the number of games played.
#' @return  The function returns a table with proportions of LOSE and WIN
#'          outcomes associated with each strategy.
#' @examples
#'   play_n_games(n = 100)
#' @export
play_n_games <- function( n=100 )
{
  
  library( dplyr )
  results.list <- list()   # collector
  loop.count <- 1
  
  for( i in 1:n )  # iterator
  {
    game.outcome <- play_game()
    results.list[[ loop.count ]] <- game.outcome
    loop.count <- loop.count + 1
  }
  
  results.df <- dplyr::bind_rows( results.list )
  
  table( results.df ) %>%
    prop.table( margin=1 ) %>%  # row proportions
    round( 2 ) %>%
    print()
  
  return( results.df )
  
}

